### ISSUE TITLE
Erreur d'insertion adin

### ISSUE THREAD

**Issue by UPTODATE-DEV** [UPTODATE-DEV/web-formation#1]
![terms-illustration](https://user-images.githubusercontent.com/57248967/107122653-9ee89c80-68a1-11eb-81be-758c298c16bd.png)
Il y en a pas ...
Au faite je vais sur la page tout s'affiche mais quand je vajis dans la BDD rien.

Pour le mdp j'ai laisse par défaut.

--------------------------------------------------------------------
<?php
try
{
    $bdd = new PDO('mysql:host=localhost;dbname=pense-bete', 'root', '');
}
catch(Exception $e)
{
        die('Erreur : '.$e->getMessage());
}
 
// On ajoute une entrée dans la table jeux_video
$req = $bdd->prepare('INSERT INTO compte(pseudo, pass, mail, ip) VALUES(:pseudo, :pass:, :mail, :ip)');
$req->execute(array('pseudo' => $_POST['pseudo'],'pass' => $_POST['pass'],'mail' => $_POST['mail'],'ip' => $_SERVER['REMOTE_ADDR']));
 
?>

**Comment by Abelbinkandanda** [comment]
oui il y a une erreur
